services:
  db:
    image: mysql:latest
    container_name: mysqldb-epic_eats
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epic_eats
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # Esta línea extra carga tu SQL automáticamente al iniciar:
      - ./epic_eats.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
  # docker compose up -d
  # docker compose down